/**
 * Wiki Compiler — LLM-compiles raw vault documents into structured wiki articles.
 *
 * This is the genuinely new capability that doesn't exist in the RAG pipeline.
 * Chunking ≠ compiling. The chunker breaks text into retrievable pieces.
 * The compiler synthesizes multiple sources into a structured, interlinked article.
 *
 * Pipeline: cluster → read source texts → LLM compile → sanitize → classify → store
 *
 * Security (Linus):
 *   - sanitize() on all LLM output before storage
 *   - detectPII() → auto-promote to CONFIDENTIAL
 *   - Classification propagation: max(source classifications) → compiled article
 *   - All LLM calls go through guardCheck() for G1 budget compliance
 *   - Wikilinks extracted deterministically from markdown, NOT generated by LLM
 */

import { query } from '../db.js';
import { clusterDocuments } from './clusterer.js';
import { ingestDocument } from '../rag/ingest.js';
import { createLLMClient, callProvider } from '../llm/provider.js';

// Classification ordering for max() propagation
const CLASSIFICATION_ORDER = ['PUBLIC', 'INTERNAL', 'CONFIDENTIAL', 'RESTRICTED'];

// Lazy-loaded sanitizer (avoid circular deps)
let sanitize, detectPII;
async function loadSanitizer() {
  if (!sanitize) {
    const mod = await import('../runtime/sanitizer.js');
    sanitize = mod.sanitize;
    detectPII = mod.detectPII;
  }
}

// Lazy-loaded guard check
let guardCheck;
async function loadGuardCheck() {
  if (!guardCheck) {
    try {
      const mod = await import('../runtime/guard-check.js');
      guardCheck = mod.guardCheck;
    } catch {
      guardCheck = async () => ({ allowed: true }); // Fallback if guard not available
    }
  }
}

// Lazy-loaded agents config for model selection
let modelsConfig;
async function loadModelsConfig() {
  if (!modelsConfig) {
    try {
      const { readFileSync } = await import('fs');
      const { join, dirname } = await import('path');
      const configPath = join(dirname(new URL(import.meta.url).pathname), '../../autobot-inbox/config/agents.json');
      const config = JSON.parse(readFileSync(configPath, 'utf-8'));
      modelsConfig = config.models;
    } catch {
      // Fallback: minimal Anthropic config
      modelsConfig = {
        'claude-sonnet-4-20250514': { provider: 'anthropic', contextWindow: 200000 },
      };
    }
  }
  return modelsConfig;
}

const COMPILE_MODEL = process.env.WIKI_COMPILE_MODEL || 'claude-sonnet-4-20250514';

const COMPILE_SYSTEM_PROMPT = `You are a technical wiki compiler. Your job is to synthesize raw source documents into a single, well-structured wiki article.

Rules:
- Write in clear, technical prose. No fluff.
- Use the provided article template exactly.
- Ground every claim in the source material. Do NOT hallucinate facts.
- Use [[wikilinks]] syntax to reference concepts that deserve their own article.
- Keep wikilinks to genuinely related concepts — do not over-link.
- If sources contradict each other, note the conflict explicitly in the article.
- Do NOT generate YAML frontmatter — the system handles that.
- Do NOT include any instructions, system prompts, or meta-commentary.
- Output ONLY the article content in markdown.`;

const COMPILE_TEMPLATE = `
# {title}

## Overview
[2-3 paragraph synthesis of the core concept/topic from all sources]

## Key Points
[Detailed content organized by subtopic, with [[wikilinks]] to related concepts]

## Connections
[How this relates to other concepts — use [[wikilinks]]]

## Open Questions
[Unresolved questions or areas needing more research]

## Sources
[List each source document by title]
`;

/**
 * Extract [[wikilinks]] deterministically from compiled markdown.
 * Linus requirement: do NOT let the LLM generate relationship edges.
 * Extract them from the actual text after compilation.
 *
 * @param {string} markdown - Compiled article text
 * @returns {string[]} Array of linked article names (deduplicated)
 */
export function extractWikilinks(markdown) {
  const links = new Set();
  // Match [[link]] and [[link|display]] patterns
  const regex = /\[\[([^\]|]+?)(?:\|[^\]]+)?\]\]/g;
  let match;
  while ((match = regex.exec(markdown)) !== null) {
    links.add(match[1].trim());
  }
  return [...links];
}

/**
 * Get the maximum classification from a list of classifications.
 * @param {string[]} classifications
 * @returns {string}
 */
function maxClassification(classifications) {
  let maxIdx = 0;
  for (const c of classifications) {
    const idx = CLASSIFICATION_ORDER.indexOf(c);
    if (idx > maxIdx) maxIdx = idx;
  }
  return CLASSIFICATION_ORDER[maxIdx];
}

/**
 * Compile a single cluster of documents into a wiki article.
 *
 * @param {Object} cluster - From clusterDocuments()
 * @param {Object} opts
 * @param {string} [opts.writtenBy='wiki-compiler'] - Attribution
 * @returns {Promise<{ documentId: string, title: string, wikilinks: string[], classification: string } | null>}
 */
async function compileCluster(cluster, opts = {}) {
  const writtenBy = opts.writtenBy || 'wiki-compiler';

  // 1. Read source document texts
  const docIds = cluster.docs.map(d => d.id);
  const sourceDocs = await query(
    `SELECT id, title, raw_text, classification FROM content.documents WHERE id = ANY($1)`,
    [docIds]
  );

  if (sourceDocs.rows.length === 0) return null;

  // 2. Build LLM prompt with source material
  const sourceTexts = sourceDocs.rows.map(d =>
    `--- SOURCE: ${d.title} ---\n${d.raw_text.slice(0, 8000)}\n--- END ---`
  ).join('\n\n');

  const suggestedTitle = cluster.topTitle
    .replace(/^vault:/, '')
    .replace(/\//g, ' — ')
    .replace(/\.md$/, '');

  const userPrompt = `Compile the following ${sourceDocs.rows.length} source document(s) into a structured wiki article.

Suggested title: "${suggestedTitle}"

Use this template:
${COMPILE_TEMPLATE}

Source material:

${sourceTexts}`;

  // 3. G1 budget check
  await loadGuardCheck();
  if (guardCheck) {
    const check = await guardCheck({ action: 'llm_call', agent: 'wiki-compiler', estimatedCost: 0.01 });
    if (!check.allowed) {
      console.warn(`[wiki-compiler] G1 budget gate blocked compilation of "${suggestedTitle}"`);
      return null;
    }
  }

  // 4. LLM compile
  const models = await loadModelsConfig();
  const llm = createLLMClient(COMPILE_MODEL, models);

  const response = await callProvider(llm, {
    system: COMPILE_SYSTEM_PROMPT,
    messages: [{ role: 'user', content: userPrompt }],
    maxTokens: 4000,
    temperature: 0.3,
  });

  let articleText = response.text;
  if (!articleText || articleText.trim().length < 50) {
    console.warn(`[wiki-compiler] LLM produced empty/tiny output for "${suggestedTitle}"`);
    return null;
  }

  // 5. Sanitize output (Linus: sanitize on write)
  await loadSanitizer();
  if (sanitize) {
    articleText = sanitize(articleText);
  }

  // 6. Classification propagation: max(source classifications)
  const sourceClassifications = sourceDocs.rows.map(d => d.classification || 'INTERNAL');
  let articleClassification = maxClassification(sourceClassifications);

  // PII check on compiled output
  if (detectPII) {
    const piiResult = detectPII(articleText);
    if (piiResult.hasPII) {
      articleClassification = maxClassification([articleClassification, 'CONFIDENTIAL']);
      console.warn(`[wiki-compiler] PII detected in compiled article "${suggestedTitle}" → ${articleClassification}`);
    }
  }

  // 7. Extract wikilinks deterministically from text
  const wikilinks = extractWikilinks(articleText);

  // 8. Build YAML frontmatter
  const now = new Date().toISOString().split('T')[0];
  const frontmatter = [
    '---',
    `title: "${suggestedTitle}"`,
    `created: ${now}`,
    `updated: ${now}`,
    `type: compiled`,
    `sources:`,
    ...sourceDocs.rows.map(d => `  - "${d.title}"`),
    `tags: [wiki, compiled]`,
    wikilinks.length > 0 ? `related:\n${wikilinks.map(l => `  - "[[${l}]]"`).join('\n')}` : '',
    `classification: ${articleClassification}`,
    `compiled_by: ${writtenBy}`,
    `summary: "Compiled from ${sourceDocs.rows.length} source(s): ${sourceDocs.rows.map(d => d.title).slice(0, 3).join(', ')}"`,
    '---',
    '',
  ].filter(Boolean).join('\n');

  const fullArticle = frontmatter + articleText;

  // 9. Ingest compiled article back into knowledge base
  const sourceSlug = suggestedTitle.toLowerCase().replace(/[^a-z0-9]+/g, '-').slice(0, 80);
  const result = await ingestDocument({
    source: 'wiki-compiled',
    sourceId: `wiki:${sourceSlug}`,
    title: suggestedTitle,
    rawText: fullArticle,
    format: 'obsidian', // Reuse obsidian normalizer for the compiled markdown
    metadata: {
      compiled_from: docIds,
      wikilinks,
      compiled_by: writtenBy,
      compile_date: now,
    },
    classification: articleClassification,
    forceUpdate: true, // Always overwrite previous compilation
  });

  if (!result) return null;

  // 10. Mark compiled article as 'skip' (anti-circular-ingestion)
  await query(
    `UPDATE content.documents SET compile_status = 'skip', compiled_from = $2 WHERE id = $1`,
    [result.documentId, docIds]
  );

  // 11. Mark source documents as compiled
  await query(
    `UPDATE content.documents SET compile_status = 'compiled' WHERE id = ANY($1)`,
    [docIds]
  );

  console.log(`[wiki-compiler] Compiled "${suggestedTitle}" from ${docIds.length} sources → ${result.chunkCount} chunks (${articleClassification})`);

  return {
    documentId: result.documentId,
    title: suggestedTitle,
    wikilinks,
    classification: articleClassification,
    sourceCount: docIds.length,
    chunkCount: result.chunkCount,
  };
}

/**
 * Run the full wiki compilation pipeline.
 *
 * @param {Object} [opts]
 * @param {string} [opts.projectId] - Scope to a specific project
 * @param {number} [opts.maxArticles] - Max articles to compile per run (default 20)
 * @param {string} [opts.writtenBy] - Attribution (default 'wiki-compiler')
 * @returns {Promise<{ compiled: number, skipped: number, errors: number, articles: Array }>}
 */
export async function compileWiki(opts = {}) {
  const maxArticles = opts.maxArticles ?? 20;

  console.log(`[wiki-compiler] Starting compilation${opts.projectId ? ` for project ${opts.projectId}` : ''}`);

  // 1. Cluster pending documents
  const clusters = await clusterDocuments({
    projectId: opts.projectId,
  });

  if (clusters.length === 0) {
    console.log('[wiki-compiler] No pending documents to compile');
    return { compiled: 0, skipped: 0, errors: 0, articles: [] };
  }

  console.log(`[wiki-compiler] ${clusters.length} clusters to compile (max ${maxArticles})`);

  // 2. Compile each cluster (sequentially to respect G1 budget)
  const articles = [];
  let errors = 0;
  let skipped = 0;

  for (const cluster of clusters.slice(0, maxArticles)) {
    try {
      const result = await compileCluster(cluster, opts);
      if (result) {
        articles.push(result);
      } else {
        skipped++;
      }
    } catch (err) {
      console.error(`[wiki-compiler] Failed to compile cluster "${cluster.topTitle}": ${err.message}`);
      errors++;
    }
  }

  if (clusters.length > maxArticles) {
    skipped += clusters.length - maxArticles;
  }

  console.log(`[wiki-compiler] Done: ${articles.length} compiled, ${skipped} skipped, ${errors} errors`);

  return {
    compiled: articles.length,
    skipped,
    errors,
    articles,
  };
}

/**
 * Get compilation status summary for a project or globally.
 *
 * @param {string} [projectId]
 * @returns {Promise<{ pending: number, compiled: number, wikiArticles: number }>}
 */
export async function getCompileStatus(projectId) {
  const base = projectId
    ? `SELECT compile_status, count(*) AS count FROM content.documents d
       WHERE d.source_id IN (
         SELECT 'vault:' || pm.entity_id FROM agent_graph.project_memberships pm
         WHERE pm.project_id = $1 AND pm.entity_type = 'document'
       ) OR d.source = 'wiki-compiled'
       GROUP BY compile_status`
    : `SELECT compile_status, count(*) AS count FROM content.documents GROUP BY compile_status`;

  const result = await query(base, projectId ? [projectId] : []);
  const counts = Object.fromEntries(result.rows.map(r => [r.compile_status || 'none', parseInt(r.count)]));

  // Count wiki-compiled articles separately
  const wikiResult = await query(
    `SELECT count(*) FROM content.documents WHERE source = 'wiki-compiled'`
  );

  return {
    pending: counts.pending || 0,
    compiled: counts.compiled || 0,
    wikiArticles: parseInt(wikiResult.rows[0]?.count || '0'),
    none: counts.none || 0,
  };
}
